import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StateProvider from '@/context/StateProvider'
import Sidebar from '@/components/Sidebar'
import { getSections } from '@/fetch'
import { Section } from '@prisma/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const sections: Section[] = await getSections()
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <StateProvider>
          <main className="flex p-4">
            <div className="p-5">
              <Sidebar initialData={sections} />
            </div>
            <div className="p-5">{children}</div>
          </main>
        </StateProvider>
      </body>
    </html>
  )
}
